# Generated by Django 2.0.5 on 2019-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191219_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reserves',
            field=models.IntegerField(),
        ),
    ]
