# Generated by Django 2.0.5 on 2019-12-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
